In [112]:
import pandas as pd
import numpy as np
import datetime
from datetime import timedelta

In [113]:
#tasked to find for each combination, what is the first day you see in the week, what is the last day you see in the week
#and how many days consecutively are missing after the first date they are seen
df = pd.read_csv('C:/Users/culle/Documents/ratios/futures.csv')

In [114]:
df.head()

,Unnamed: 0,clientInsertReqTimestamp,exchangeRspLatency,exchangeRtnLatency,clientIp,counterIp,exchangeIp,accountRef,clientId,userId,instrumentId,combOffsetFlag,direction,limitPrice
0,0,2022-10-23 17:25:27.000,7711160024,18905385651,10.71.226.26,10.71.226.193,172.24.16.57,16,1157870,000191,IC2211,CLOSE,BUY,6537.4
1,1,2022-10-23 17:25:27.000,19007582817,19007582817,10.71.226.26,10.71.226.193,172.24.16.52,16,1157870,000188,IC2212,CLOSE,BUY,6512.2
2,2,2022-10-23 17:25:27.000,10751578828,19091437328,10.71.226.26,10.71.226.193,172.24.16.54,16,1157870,000190,IC2211,CLOSE,SELL,5349.0
3,3,2022-10-23 17:25:27.000,11230564306,19096583004,10.71.226.26,10.71.226.193,172.24.16.53,16,1157870,000189,IC2212,CLOSE,SELL,5328.2
4,4,2022-10-23 17:30:27.000,39207621194,39329185199,10.71.226.26,10.71.226.193,172.24.16.52,16,1157870,000188,IM2212,CLOSE,SELL,6321.6

In [115]:
#determine the dates/week to include, make a new data frame
df['clientInsertReqTimestamp'] = pd.to_datetime(df['clientInsertReqTimestamp'])
latest_date = df['clientInsertReqTimestamp'].max()
start_date = latest_date - datetime.timedelta(days=6)
lastSevenDays = df.loc[df['clientInsertReqTimestamp'] >= start_date]
lastSevenDays.head()

,Unnamed: 0,clientInsertReqTimestamp,exchangeRspLatency,exchangeRtnLatency,clientIp,counterIp,exchangeIp,accountRef,clientId,userId,instrumentId,combOffsetFlag,direction,limitPrice
9354019,9354019,2022-12-05 01:31:23.818,52315025658,52332050018,10.71.226.26,10.71.226.193,172.24.16.55,2,1323356,000193,IM2303,CLOSE,BUY,6641.2
9354020,9354020,2022-12-05 01:31:23.818,52381638105,52487630675,10.71.226.26,10.71.226.193,172.24.16.54,4,1437060,000190,IF2306,CLOSE,SELL,3942.8
9354021,9354021,2022-12-05 01:31:23.818,55423127125,55295162939,10.71.226.26,10.71.226.193,172.24.16.57,4,1437060,000191,IM2301,CLOSE,SELL,6706.4
9354022,9354022,2022-12-05 01:31:23.818,61727613636,61839673508,10.71.226.26,10.71.226.193,172.24.16.59,3,1495295,000192,IM2303,CLOSE,BUY,6641.2
9354023,9354023,2022-12-05 01:31:23.818,63390687470,63390687470,10.71.226.26,10.71.226.230,172.24.16.56,1,1411795,0001F0,IM2303,CLOSE,BUY,6641.2

In [116]:
#remove the time from the date
lastSevenDays['clientInsertReqTimestamp'] = pd.to_datetime(lastSevenDays['clientInsertReqTimestamp']).dt.date
lastSevenDays.head()

C:\Users\culle\AppData\Local\Temp\ipykernel_10412\3206954346.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lastSevenDays['clientInsertReqTimestamp'] = pd.to_datetime(lastSevenDays['clientInsertReqTimestamp']).dt.date

,Unnamed: 0,clientInsertReqTimestamp,exchangeRspLatency,exchangeRtnLatency,clientIp,counterIp,exchangeIp,accountRef,clientId,userId,instrumentId,combOffsetFlag,direction,limitPrice
9354019,9354019,2022-12-05,52315025658,52332050018,10.71.226.26,10.71.226.193,172.24.16.55,2,1323356,000193,IM2303,CLOSE,BUY,6641.2
9354020,9354020,2022-12-05,52381638105,52487630675,10.71.226.26,10.71.226.193,172.24.16.54,4,1437060,000190,IF2306,CLOSE,SELL,3942.8
9354021,9354021,2022-12-05,55423127125,55295162939,10.71.226.26,10.71.226.193,172.24.16.57,4,1437060,000191,IM2301,CLOSE,SELL,6706.4
9354022,9354022,2022-12-05,61727613636,61839673508,10.71.226.26,10.71.226.193,172.24.16.59,3,1495295,000192,IM2303,CLOSE,BUY,6641.2
9354023,9354023,2022-12-05,63390687470,63390687470,10.71.226.26,10.71.226.230,172.24.16.56,1,1411795,0001F0,IM2303,CLOSE,BUY,6641.2

In [117]:
#remove unneccessary variables
del lastSevenDays['combOffsetFlag']
del lastSevenDays['direction']
del lastSevenDays['limitPrice']
del lastSevenDays['accountRef']
del lastSevenDays['userId']
del lastSevenDays['clientId']

In [118]:
#sort the earliest dates
subsetCols = ['clientIp','exchangeIp','counterIp','instrumentId']
lastSevenDays['earliestDate'] = lastSevenDays.groupby(subsetCols)['clientInsertReqTimestamp'].transform('min')
lastSevenDays.head()

C:\Users\culle\AppData\Local\Temp\ipykernel_10412\1307534862.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lastSevenDays['earliestDate'] = lastSevenDays.groupby(subsetCols)['clientInsertReqTimestamp'].transform('min')

,Unnamed: 0,clientInsertReqTimestamp,exchangeRspLatency,exchangeRtnLatency,clientIp,counterIp,exchangeIp,instrumentId,earliestDate
9354019,9354019,2022-12-05,52315025658,52332050018,10.71.226.26,10.71.226.193,172.24.16.55,IM2303,2022-12-05
9354020,9354020,2022-12-05,52381638105,52487630675,10.71.226.26,10.71.226.193,172.24.16.54,IF2306,2022-12-05
9354021,9354021,2022-12-05,55423127125,55295162939,10.71.226.26,10.71.226.193,172.24.16.57,IM2301,2022-12-05
9354022,9354022,2022-12-05,61727613636,61839673508,10.71.226.26,10.71.226.193,172.24.16.59,IM2303,2022-12-05
9354023,9354023,2022-12-05,63390687470,63390687470,10.71.226.26,10.71.226.230,172.24.16.56,IM2303,2022-12-05

In [119]:
# the latest date
subsetCols = ['clientIp','exchangeIp','counterIp','instrumentId']
lastSevenDays['lastestDate'] = lastSevenDays.groupby(subsetCols)['clientInsertReqTimestamp'].transform('max')
lastSevenDays.head()

C:\Users\culle\AppData\Local\Temp\ipykernel_10412\1385707410.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lastSevenDays['lastestDate'] = lastSevenDays.groupby(subsetCols)['clientInsertReqTimestamp'].transform('max')

,Unnamed: 0,clientInsertReqTimestamp,exchangeRspLatency,exchangeRtnLatency,clientIp,counterIp,exchangeIp,instrumentId,earliestDate,lastestDate
9354019,9354019,2022-12-05,52315025658,52332050018,10.71.226.26,10.71.226.193,172.24.16.55,IM2303,2022-12-05,2022-12-09
9354020,9354020,2022-12-05,52381638105,52487630675,10.71.226.26,10.71.226.193,172.24.16.54,IF2306,2022-12-05,2022-12-05
9354021,9354021,2022-12-05,55423127125,55295162939,10.71.226.26,10.71.226.193,172.24.16.57,IM2301,2022-12-05,2022-12-09
9354022,9354022,2022-12-05,61727613636,61839673508,10.71.226.26,10.71.226.193,172.24.16.59,IM2303,2022-12-05,2022-12-09
9354023,9354023,2022-12-05,63390687470,63390687470,10.71.226.26,10.71.226.230,172.24.16.56,IM2303,2022-12-05,2022-12-07

In [120]:
#get the difference between the current date, and the earliest date
lastSevenDays['daysMissing'] = lastSevenDays['clientInsertReqTimestamp'] - lastSevenDays['earliestDate']
lastSevenDays['daysMissing'] = pd.to_timedelta(lastSevenDays['daysMissing']).dt.days
lastSevenDays.head()

C:\Users\culle\AppData\Local\Temp\ipykernel_10412\2047862007.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lastSevenDays['daysMissing'] = lastSevenDays['clientInsertReqTimestamp'] - lastSevenDays['earliestDate']
C:\Users\culle\AppData\Local\Temp\ipykernel_10412\2047862007.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lastSevenDays['daysMissing'] = pd.to_timedelta(lastSevenDays['daysMissing']).dt.days

,Unnamed: 0,clientInsertReqTimestamp,exchangeRspLatency,exchangeRtnLatency,clientIp,counterIp,exchangeIp,instrumentId,earliestDate,lastestDate,daysMissing
9354019,9354019,2022-12-05,52315025658,52332050018,10.71.226.26,10.71.226.193,172.24.16.55,IM2303,2022-12-05,2022-12-09,0
9354020,9354020,2022-12-05,52381638105,52487630675,10.71.226.26,10.71.226.193,172.24.16.54,IF2306,2022-12-05,2022-12-05,0
9354021,9354021,2022-12-05,55423127125,55295162939,10.71.226.26,10.71.226.193,172.24.16.57,IM2301,2022-12-05,2022-12-09,0
9354022,9354022,2022-12-05,61727613636,61839673508,10.71.226.26,10.71.226.193,172.24.16.59,IM2303,2022-12-05,2022-12-09,0
9354023,9354023,2022-12-05,63390687470,63390687470,10.71.226.26,10.71.226.230,172.24.16.56,IM2303,2022-12-05,2022-12-07,0

In [121]:
#delete unneccessary columns
del lastSevenDays['Unnamed: 0']
del lastSevenDays['exchangeRspLatency']
del lastSevenDays['exchangeRtnLatency']

In [122]:
#drop the trades that happened on the same date, then sort the daysMissing column by the minimum,
#then you can drop duplicates to get the next date that you see this group being used

mask = (lastSevenDays.iloc[:, 7] != 0) | (lastSevenDays.iloc[:, 5] == lastSevenDays.iloc[:, 6])

# Filter the DataFrame using the boolean mask
lastSevenDays = lastSevenDays[mask].reset_index(drop=True)

In [124]:
lastSevenDays.tail()

,clientInsertReqTimestamp,clientIp,counterIp,exchangeIp,instrumentId,earliestDate,lastestDate,daysMissing
1624328,2022-12-09,10.71.226.129,10.71.226.193,172.24.16.53,T2303,2022-12-05,2022-12-09,4
1624329,2022-12-09,10.71.226.129,10.71.226.193,172.24.16.55,T2303,2022-12-05,2022-12-09,4
1624330,2022-12-09,10.71.226.129,10.71.226.193,172.24.16.57,T2303,2022-12-05,2022-12-09,4
1624331,2022-12-09,10.71.226.129,10.71.226.193,172.24.16.59,T2303,2022-12-05,2022-12-09,4
1624332,2022-12-09,10.71.226.129,10.71.226.193,172.24.16.58,T2303,2022-12-05,2022-12-09,4

In [126]:
#group by subset, sort by having the minimum first
subsetCols = ['clientIp','exchangeIp','counterIp','instrumentId']
lastSevenDays['daysMissing'] = lastSevenDays.groupby(subsetCols)['daysMissing'].transform('min')
lastSevenDays.tail()

,clientInsertReqTimestamp,clientIp,counterIp,exchangeIp,instrumentId,earliestDate,lastestDate,daysMissing
1624328,2022-12-09,10.71.226.129,10.71.226.193,172.24.16.53,T2303,2022-12-05,2022-12-09,1
1624329,2022-12-09,10.71.226.129,10.71.226.193,172.24.16.55,T2303,2022-12-05,2022-12-09,1
1624330,2022-12-09,10.71.226.129,10.71.226.193,172.24.16.57,T2303,2022-12-05,2022-12-09,1
1624331,2022-12-09,10.71.226.129,10.71.226.193,172.24.16.59,T2303,2022-12-05,2022-12-09,1
1624332,2022-12-09,10.71.226.129,10.71.226.193,172.24.16.58,T2303,2022-12-05,2022-12-09,1

In [127]:
#delete duplicates
uniqueLastSevenDays = lastSevenDays.drop_duplicates(subset = ['clientIp','exchangeIp','counterIp','instrumentId'])

In [130]:
uniqueLastSevenDays.head()

,clientInsertReqTimestamp,clientIp,counterIp,exchangeIp,instrumentId,earliestDate,lastestDate,daysMissing
0,2022-12-05,10.71.226.26,10.71.226.193,172.24.16.54,IF2306,2022-12-05,2022-12-05,0
1,2022-12-05,10.71.226.133,10.71.226.230,172.24.16.53,IO2212-C-3900,2022-12-05,2022-12-05,0
2,2022-12-05,10.71.243.17,10.71.243.201,172.24.16.57,IC2301,2022-12-05,2022-12-05,0
3,2022-12-05,10.71.226.116,10.71.226.222,172.24.16.51,IH2212,2022-12-05,2022-12-05,0
4,2022-12-05,10.71.243.17,10.71.243.201,172.24.16.55,IC2212,2022-12-05,2022-12-05,0

In [131]:
uniqueLastSevenDays.tail()

,clientInsertReqTimestamp,clientIp,counterIp,exchangeIp,instrumentId,earliestDate,lastestDate,daysMissing
1621748,2022-12-09,10.71.226.109,10.71.226.198,172.24.16.54,T2303,2022-12-06,2022-12-09,3
1621749,2022-12-09,10.71.226.109,10.71.226.198,172.24.16.57,T2303,2022-12-06,2022-12-09,3
1621751,2022-12-09,10.71.226.109,10.71.226.198,172.24.16.55,T2303,2022-12-06,2022-12-09,3
1621752,2022-12-09,10.71.226.109,10.71.226.198,172.24.16.58,T2303,2022-12-06,2022-12-09,3
1621760,2022-12-09,10.71.226.109,10.71.226.198,172.24.16.51,T2303,2022-12-06,2022-12-09,3