In [70]:
import pandas as pd
import numpy as np
import datetime
from datetime import timedelta

In [71]:
df = pd.read_csv('C:/Users/culle/Documents/ratios/futures.csv')

In [72]:
df.head()

,Unnamed: 0,clientInsertReqTimestamp,exchangeRspLatency,exchangeRtnLatency,clientIp,counterIp,exchangeIp,accountRef,clientId,userId,instrumentId,combOffsetFlag,direction,limitPrice
0,0,2022-10-23 17:25:27.000,7711160024,18905385651,10.71.226.26,10.71.226.193,172.24.16.57,16,1157870,000191,IC2211,CLOSE,BUY,6537.4
1,1,2022-10-23 17:25:27.000,19007582817,19007582817,10.71.226.26,10.71.226.193,172.24.16.52,16,1157870,000188,IC2212,CLOSE,BUY,6512.2
2,2,2022-10-23 17:25:27.000,10751578828,19091437328,10.71.226.26,10.71.226.193,172.24.16.54,16,1157870,000190,IC2211,CLOSE,SELL,5349.0
3,3,2022-10-23 17:25:27.000,11230564306,19096583004,10.71.226.26,10.71.226.193,172.24.16.53,16,1157870,000189,IC2212,CLOSE,SELL,5328.2
4,4,2022-10-23 17:30:27.000,39207621194,39329185199,10.71.226.26,10.71.226.193,172.24.16.52,16,1157870,000188,IM2212,CLOSE,SELL,6321.6

In [73]:
#Determine the date that was from max date - 7 days ago
df['clientInsertReqTimestamp'] = pd.to_datetime(df['clientInsertReqTimestamp'])
latest_date = df['clientInsertReqTimestamp'].max()
start_date = latest_date - datetime.timedelta(days=6)
lastSevenDays = df.loc[df['clientInsertReqTimestamp'] >= start_date]
lastSevenDays.head()

,Unnamed: 0,clientInsertReqTimestamp,exchangeRspLatency,exchangeRtnLatency,clientIp,counterIp,exchangeIp,accountRef,clientId,userId,instrumentId,combOffsetFlag,direction,limitPrice
9354019,9354019,2022-12-05 01:31:23.818,52315025658,52332050018,10.71.226.26,10.71.226.193,172.24.16.55,2,1323356,000193,IM2303,CLOSE,BUY,6641.2
9354020,9354020,2022-12-05 01:31:23.818,52381638105,52487630675,10.71.226.26,10.71.226.193,172.24.16.54,4,1437060,000190,IF2306,CLOSE,SELL,3942.8
9354021,9354021,2022-12-05 01:31:23.818,55423127125,55295162939,10.71.226.26,10.71.226.193,172.24.16.57,4,1437060,000191,IM2301,CLOSE,SELL,6706.4
9354022,9354022,2022-12-05 01:31:23.818,61727613636,61839673508,10.71.226.26,10.71.226.193,172.24.16.59,3,1495295,000192,IM2303,CLOSE,BUY,6641.2
9354023,9354023,2022-12-05 01:31:23.818,63390687470,63390687470,10.71.226.26,10.71.226.230,172.24.16.56,1,1411795,0001F0,IM2303,CLOSE,BUY,6641.2

In [74]:
#remove the time from datetime
lastSevenDays['clientInsertReqTimestamp'] = pd.to_datetime(lastSevenDays['clientInsertReqTimestamp']).dt.date
lastSevenDays.head()

C:\Users\culle\AppData\Local\Temp\ipykernel_12376\4096658468.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lastSevenDays['clientInsertReqTimestamp'] = pd.to_datetime(lastSevenDays['clientInsertReqTimestamp']).dt.date

,Unnamed: 0,clientInsertReqTimestamp,exchangeRspLatency,exchangeRtnLatency,clientIp,counterIp,exchangeIp,accountRef,clientId,userId,instrumentId,combOffsetFlag,direction,limitPrice
9354019,9354019,2022-12-05,52315025658,52332050018,10.71.226.26,10.71.226.193,172.24.16.55,2,1323356,000193,IM2303,CLOSE,BUY,6641.2
9354020,9354020,2022-12-05,52381638105,52487630675,10.71.226.26,10.71.226.193,172.24.16.54,4,1437060,000190,IF2306,CLOSE,SELL,3942.8
9354021,9354021,2022-12-05,55423127125,55295162939,10.71.226.26,10.71.226.193,172.24.16.57,4,1437060,000191,IM2301,CLOSE,SELL,6706.4
9354022,9354022,2022-12-05,61727613636,61839673508,10.71.226.26,10.71.226.193,172.24.16.59,3,1495295,000192,IM2303,CLOSE,BUY,6641.2
9354023,9354023,2022-12-05,63390687470,63390687470,10.71.226.26,10.71.226.230,172.24.16.56,1,1411795,0001F0,IM2303,CLOSE,BUY,6641.2

In [75]:
#delete unnecessary rows
del lastSevenDays['combOffsetFlag']
del lastSevenDays['direction']
del lastSevenDays['limitPrice']
del lastSevenDays['accountRef']
del lastSevenDays['userId']
del lastSevenDays['clientId']

In [76]:
lastSevenDays.head()

,Unnamed: 0,clientInsertReqTimestamp,exchangeRspLatency,exchangeRtnLatency,clientIp,counterIp,exchangeIp,instrumentId
9354019,9354019,2022-12-05,52315025658,52332050018,10.71.226.26,10.71.226.193,172.24.16.55,IM2303
9354020,9354020,2022-12-05,52381638105,52487630675,10.71.226.26,10.71.226.193,172.24.16.54,IF2306
9354021,9354021,2022-12-05,55423127125,55295162939,10.71.226.26,10.71.226.193,172.24.16.57,IM2301
9354022,9354022,2022-12-05,61727613636,61839673508,10.71.226.26,10.71.226.193,172.24.16.59,IM2303
9354023,9354023,2022-12-05,63390687470,63390687470,10.71.226.26,10.71.226.230,172.24.16.56,IM2303

In [77]:
#find out the means of the latencies, for each variable
lastSevenDays['totalLatency'] = lastSevenDays['exchangeRspLatency'] + lastSevenDays['exchangeRtnLatency']
lastSevenDays = lastSevenDays.copy()

C:\Users\culle\AppData\Local\Temp\ipykernel_12376\3341178368.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  lastSevenDays['totalLatency'] = lastSevenDays['exchangeRspLatency'] + lastSevenDays['exchangeRtnLatency']

In [81]:
#created weighted Latencies for all entries in the last 7 days, using hash table to store values of expoential weight
lastSevenDays['weightedLatency'] = 0
weights = {
    '09': 0,
    '08': 1,
    '07': 2,
    '06': 3,
    '05': 4,
    '04': 5,
}

lastSevenDays['clientInsertReqTimestamp'] = pd.to_datetime(lastSevenDays['clientInsertReqTimestamp'])
lastSevenDays['weightedLatency'] = lastSevenDays.iloc[:, 8] * pow(0.8, lastSevenDays.iloc[:, 1].dt.strftime("%d").map(weights).fillna(6))

In [82]:
#creating another df, that is only unique
#clone a new df and delete duplicates, remove excess columns
uniqueLastSevenDays = lastSevenDays
uniqueLastSevenDays = uniqueLastSevenDays.drop_duplicates(subset = ['clientIp','exchangeIp','counterIp','instrumentId'])
del uniqueLastSevenDays['Unnamed: 0']
del uniqueLastSevenDays['exchangeRspLatency']
del uniqueLastSevenDays['exchangeRtnLatency']
uniqueLastSevenDays.head()

,clientInsertReqTimestamp,clientIp,counterIp,exchangeIp,instrumentId,totalLatency,weightedLatency
9354019,2022-12-05,10.71.226.26,10.71.226.193,172.24.16.55,IM2303,104647075676,4.286344e+10
9354020,2022-12-05,10.71.226.26,10.71.226.193,172.24.16.54,IF2306,104869268780,4.295445e+10
9354021,2022-12-05,10.71.226.26,10.71.226.193,172.24.16.57,IM2301,110718290064,4.535021e+10
9354022,2022-12-05,10.71.226.26,10.71.226.193,172.24.16.59,IM2303,123567287144,5.061316e+10
9354023,2022-12-05,10.71.226.26,10.71.226.230,172.24.16.56,IM2303,126781374940,5.192965e+10

In [83]:
lastSevenDays_grouped = lastSevenDays.groupby(['clientIp', 'counterIp', 'exchangeIp', 'instrumentId'])
subset = lastSevenDays_grouped['weightedLatency'].sum() / 1000000
uniqueLastSevenDays = uniqueLastSevenDays.merge(subset, on=['clientIp', 'counterIp', 'exchangeIp', 'instrumentId'], how='left')

In [84]:
uniqueLastSevenDays.rename(columns={'weightedLatency_y':'weightedAndSmoothed'},inplace = True)
uniqueLastSevenDays.head()

,clientInsertReqTimestamp,clientIp,counterIp,exchangeIp,instrumentId,totalLatency,weightedLatency_x,weightedAndSmoothed
0,2022-12-05,10.71.226.26,10.71.226.193,172.24.16.55,IM2303,104647075676,4.286344e+10,388147.624038
1,2022-12-05,10.71.226.26,10.71.226.193,172.24.16.54,IF2306,104869268780,4.295445e+10,42954.452492
2,2022-12-05,10.71.226.26,10.71.226.193,172.24.16.57,IM2301,110718290064,4.535021e+10,274216.018576
3,2022-12-05,10.71.226.26,10.71.226.193,172.24.16.59,IM2303,123567287144,5.061316e+10,710190.396821
4,2022-12-05,10.71.226.26,10.71.226.230,172.24.16.56,IM2303,126781374940,5.192965e+10,82348.717341

In [85]:
uniqueLastSevenDays.sort_values(by = 'weightedAndSmoothed')
uniqueLastSevenDays.head()

,clientInsertReqTimestamp,clientIp,counterIp,exchangeIp,instrumentId,totalLatency,weightedLatency_x,weightedAndSmoothed
0,2022-12-05,10.71.226.26,10.71.226.193,172.24.16.55,IM2303,104647075676,4.286344e+10,388147.624038
1,2022-12-05,10.71.226.26,10.71.226.193,172.24.16.54,IF2306,104869268780,4.295445e+10,42954.452492
2,2022-12-05,10.71.226.26,10.71.226.193,172.24.16.57,IM2301,110718290064,4.535021e+10,274216.018576
3,2022-12-05,10.71.226.26,10.71.226.193,172.24.16.59,IM2303,123567287144,5.061316e+10,710190.396821
4,2022-12-05,10.71.226.26,10.71.226.230,172.24.16.56,IM2303,126781374940,5.192965e+10,82348.717341

In [86]:
#create a new df to store the medians of the top 5 for each of the last 7 days
numOccur_df = pd.DataFrame("none",index = range(5),columns=['D1', 'D2', 'D3', 'D4', 'D5', 'D6', 'D7'])

In [87]:
result_df = uniqueLastSevenDays.head(5)
del result_df['clientInsertReqTimestamp']
del result_df['totalLatency']
del result_df['weightedLatency_x']
result_df.head()

       clientIp      counterIp    exchangeIp instrumentId  weightedAndSmoothed
0  10.71.226.26  10.71.226.193  172.24.16.55       IM2303        388147.624038
1  10.71.226.26  10.71.226.193  172.24.16.54       IF2306         42954.452492
2  10.71.226.26  10.71.226.193  172.24.16.57       IM2301        274216.018576
3  10.71.226.26  10.71.226.193  172.24.16.59       IM2303        710190.396821
4  10.71.226.26  10.71.226.230  172.24.16.56       IM2303         82348.717341

In [88]:
#creating the medians of the top 5 latencies for each day
for i in range(5):
    startDate = datetime.datetime(2022,12,3) 
    client = result_df.iloc[i,0]
    counter = result_df.iloc[i,1]
    exchange = result_df.iloc[i,2]
    instrument = result_df.iloc[i,3]
    for j in range(7):
        subset = lastSevenDays[(lastSevenDays['clientIp'] == client) & 
                       (lastSevenDays['counterIp'] == counter) & 
                       (lastSevenDays['exchangeIp'] == exchange) & 
                       (lastSevenDays['instrumentId'] == instrument) &
                       (lastSevenDays['clientInsertReqTimestamp'].dt.date  == startDate.date())]
        latency = subset['totalLatency'].median() / 1000000
        if latency == 0:
            numOccur_df.iloc[i,j] = "NaN"
        else:
            numOccur_df.iloc[i,j] = latency
            
        startDate += timedelta(days = 1)
        
numOccur_df.head()

,D1,D2,D3,D4,D5,D6,D7
0,NaN,NaN,67607.853164,19891.295933,NaN,6990.720773,14297.064779
1,NaN,NaN,104869.26878,NaN,NaN,NaN,NaN
2,NaN,NaN,18730.62524,NaN,NaN,NaN,29291.674661
3,NaN,NaN,11634.861758,14737.255246,6698.87957,9184.577812,13070.95963
4,NaN,NaN,126781.37494,20658.220447,7238.319083,NaN,NaN

In [95]:
#change ratio
result_df['changeRatio'] = 0
for i in range(5):
    client = result_df.iloc[i,0]
    counter = result_df.iloc[i,1]
    exchange = result_df.iloc[i,2]
    instrument = result_df.iloc[i,3]
    subset = lastSevenDays[(lastSevenDays['clientIp'] == client) & 
                       (lastSevenDays['counterIp'] == counter) & 
                       (lastSevenDays['exchangeIp'] == exchange) & 
                       (lastSevenDays['instrumentId'] == instrument)]
    max = subset['totalLatency'].max() / 1000000
    min = subset['totalLatency'].min() / 1000000
    ratio = (max - min) / min
    result_df.iloc[i,5] = ratio

C:\Users\culle\AppData\Local\Temp\ipykernel_12376\399043377.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df['changeRatio'] = 0

In [90]:
#efficiency ratio
result_df['effRatio'] = 0
for i in range(5):
    client = result_df.iloc[i,0]
    counter = result_df.iloc[i,1]
    exchange = result_df.iloc[i,2]
    instrument = result_df.iloc[i,3]
    subset = lastSevenDays[(lastSevenDays['clientIp'] == client) & 
                       (lastSevenDays['counterIp'] == counter) & 
                       (lastSevenDays['exchangeIp'] == exchange) & 
                       (lastSevenDays['instrumentId'] == instrument)]
    ratio = subset['clientInsertReqTimestamp'].nunique()
    result_df.iloc[i,6] = ratio/7

C:\Users\culle\AppData\Local\Temp\ipykernel_12376\3808702654.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df['effRatio'] = 0

In [96]:
#final results
result_df.head()

,clientIp,counterIp,exchangeIp,instrumentId,weightedAndSmoothed,changeRatio,effRatio
0,10.71.226.26,10.71.226.193,172.24.16.55,IM2303,388147.624038,30.565731,0.571429
1,10.71.226.26,10.71.226.193,172.24.16.54,IF2306,42954.452492,0.000000,0.142857
2,10.71.226.26,10.71.226.193,172.24.16.57,IM2301,274216.018576,22.916189,0.285714
3,10.71.226.26,10.71.226.193,172.24.16.59,IM2303,710190.396821,65.361106,0.714286
4,10.71.226.26,10.71.226.230,172.24.16.56,IM2303,82348.717341,19.692901,0.428571

In [97]:
numOccur_df.head()

,D1,D2,D3,D4,D5,D6,D7
0,NaN,NaN,67607.853164,19891.295933,NaN,6990.720773,14297.064779
1,NaN,NaN,104869.26878,NaN,NaN,NaN,NaN
2,NaN,NaN,18730.62524,NaN,NaN,NaN,29291.674661
3,NaN,NaN,11634.861758,14737.255246,6698.87957,9184.577812,13070.95963
4,NaN,NaN,126781.37494,20658.220447,7238.319083,NaN,NaN